export { default as Navigation } from "./Navigation";
export {default as Team} from './Team';
export {default as Attend} from './Attend';
export {default as Contactus} from './Contactus';
export {default as Conductor} from './Conductor';
export {default as Teleportation} from './Teleportation';
export {default as Legacy} from './Legacy';
export {default as Tangram} from './Tangram';
export {default as Home} from './Home';
export {default as Sponsers} from './Sponsers';
export {default as Watch} from './Watch';
export {default as Footer} from './Footer';
// export {default as slider} from './slider';
